spring.application.name=backend

server.port=8080

#spring.datasource.url=jdbc:mysql://localhost:3306/trackiq?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
#spring.datasource.username=root
#spring.datasource.password=Lucky@12
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# ===============================
# ? AIVEN MYSQL DATABASE CONFIG
# ===============================
spring.datasource.url=jdbc:mysql://mysql-1aba8c72-trackiq.aivencloud.com:20383/defaultdb?ssl-mode=REQUIRED&useSSL=true&requireSSL=true&verifyServerCertificate=false

spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.connection-timeout=30000
# ===============================
# ? JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ===============================
# ? EMAIL CONFIG (keep yours)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vallampatlasrilaxmi20@gmail.com
spring.mail.password=kkou khth klyp ttaq

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ===============================
# ? FILE UPLOAD
# ===============================
spring.web.resources.static-locations=file:uploads/